version: '3'

services:
    web:
        build: .
        command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
    nginx:
      build:
        context: .
        dockerfile: nginx/Dockerfile
      ports:
       - 8080:80
      depends_on:
        - web