# Generated by Django 2.2.3 on 2020-06-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registro', '0006_delete_renovacao_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovacao_Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Renovacao', max_length=150, verbose_name='name')),
                ('visit_date', models.DateTimeField(blank=True, null=True, verbose_name='Data ultima visita')),
                ('date_atualizado', models.DateTimeField(blank=True, null=True, verbose_name='Data Atualizacao')),
                ('homologa', models.BooleanField(default=False, verbose_name='Homologado')),
                ('probabilidade', models.CharField(default='30%', max_length=150, verbose_name='Probabilidade de fechamento')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('next_stage', models.TextField(verbose_name='Proxima Etapa')),
                ('comments', models.TextField(verbose_name='Comentarios')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('atualizado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Registro.Registro', verbose_name='Registro')),
            ],
        ),
    ]
