# Generated by Django 2.2.3 on 2020-06-04 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 4, 14, 36, 3, 949872, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='renovacao_registro',
            name='atualizado',
            field=models.BooleanField(default=False, verbose_name='Atualizado'),
        ),
    ]
