# Generated by Django 2.2.3 on 2020-06-09 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0002_auto_20200604_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 9, 13, 34, 24, 719176, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
