# Generated by Django 2.2.3 on 2020-06-24 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0003_auto_20200609_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 12, 57, 4, 249327, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
