# Generated by Django 2.2.3 on 2020-07-13 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0005_auto_20200710_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 13, 13, 24, 9, 936803, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
