# Generated by Django 2.2.3 on 2020-07-14 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0006_auto_20200713_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 13, 31, 44, 503147, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
