# Generated by Django 2.2.3 on 2020-07-14 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0007_auto_20200714_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 13, 33, 13, 431601, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
