# Generated by Django 2.2.3 on 2020-07-17 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0009_auto_20200714_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 17, 17, 40, 2, 592470, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
