# Generated by Django 2.2.3 on 2020-07-20 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0010_auto_20200717_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 20, 18, 27, 29, 571109, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
