# Generated by Django 2.2.3 on 2020-07-20 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0012_auto_20200720_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 20, 18, 47, 16, 892084, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
