# Generated by Django 2.2.3 on 2020-07-28 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0013_auto_20200720_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 28, 12, 49, 46, 668542, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
