# Generated by Django 2.2.3 on 2020-07-29 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Renovacao', '0014_auto_20200728_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacao_registro',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 29, 12, 55, 49, 664180, tzinfo=utc), null=True, verbose_name='Data de criação'),
        ),
    ]
