# Generated by Django 2.2.3 on 2020-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0010_auto_20200316_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenda_user',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
