# Generated by Django 2.2.3 on 2020-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0003_auto_20200320_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_projeto',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
