# Generated by Django 2.2.3 on 2020-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0004_equip_projeto_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_projeto',
            name='atualizado',
            field=models.BooleanField(default=False, verbose_name='Atualiazdo'),
        ),
    ]
