# Generated by Django 2.2.3 on 2020-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0005_equip_projeto_atualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='is_concorrente',
            field=models.BooleanField(default=False, verbose_name='Concorrente'),
        ),
    ]
