# Generated by Django 2.2.3 on 2020-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipamento', '0006_equipamento_is_concorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_projeto',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
    ]
