# Generated by Django 2.2.3 on 2020-06-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0011_revenda_user_aprovado'),
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='atualizado',
            field=models.BooleanField(default=False, verbose_name='Atualizado'),
        ),
        migrations.AddField(
            model_name='registro',
            name='contato',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato Cliente'),
        ),
        migrations.AddField(
            model_name='registro',
            name='data_att_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Data Atualização Registro'),
        ),
        migrations.AddField(
            model_name='registro',
            name='date_atualizado',
            field=models.DateField(blank=True, null=True, verbose_name='Data Atualização'),
        ),
        migrations.AddField(
            model_name='registro',
            name='date_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data Validade'),
        ),
        migrations.AddField(
            model_name='registro',
            name='id_revenda_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Revenda_User', verbose_name='Revenda Usuário'),
        ),
        migrations.AddField(
            model_name='registro',
            name='marca',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='registro',
            name='name',
            field=models.CharField(default='Registro Oportunidade', max_length=150, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='registro',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Registro'),
        ),
        migrations.AddField(
            model_name='registro',
            name='registro_atualizacao',
            field=models.BooleanField(default=False, verbose_name='Registro Atualizado'),
        ),
        migrations.AddField(
            model_name='registro',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='colet_dados',
            field=models.TextField(verbose_name='Coletor de dados'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='parc_soft',
            field=models.CharField(max_length=255, verbose_name='Parceiro de software'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='id_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.Vendedor', verbose_name='Vendedor'),
        ),
    ]
