# Generated by Django 2.2.3 on 2020-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_renovacao_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovacao_registro',
            name='app_config',
            field=models.CharField(default='a', max_length=150, verbose_name='A'),
        ),
    ]
