# Generated by Django 2.2.3 on 2020-06-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_renovacao_registro_app_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renovacao_registro',
            name='app_config',
        ),
    ]
