# Generated by Django 2.2.3 on 2020-06-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_remove_renovacao_registro_app_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renovacao_Registro',
        ),
    ]
