# Generated by Django 2.2.3 on 2020-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_delete_renovacao_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='atualizado_renovado',
            field=models.BooleanField(default=False, verbose_name='Atualizado Renovação'),
        ),
        migrations.AddField(
            model_name='registro',
            name='renovado',
            field=models.BooleanField(default=False, verbose_name='Renovado'),
        ),
    ]
