# Generated by Django 2.2.3 on 2020-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_auto_20200604_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('empresa', models.CharField(max_length=250, verbose_name='Empresa')),
            ],
        ),
    ]
