# Generated by Django 2.2.3 on 2020-07-14 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_auto_20200713_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='date_concl',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Conclusão'),
        ),
    ]
