# Generated by Django 2.2.3 on 2020-07-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0010_auto_20200714_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Registro.Url', verbose_name='URL')),
            ],
        ),
    ]
