# Generated by Django 2.2.3 on 2020-07-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0012_registro_rede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='rede',
        ),
    ]
