# Generated by Django 2.2.3 on 2020-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0014_registro_rede'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='senha',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='senha'),
        ),
    ]
